import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/headers">Headers</Link>
        </li>
        <li>
          <Link to="/uikit">UIKIT</Link>
        </li>
        <li>
          <Link to="/swaptos1326">Swaptos1326</Link>
        </li>
        <li>
          <Link to="/v21920">V21920</Link>
        </li>
        <li>
          <Link to="/uikitmain360">UIKitmain360</Link>
        </li>
        <li>
          <Link to="/errorpage">Errorpage</Link>
        </li>
        <li>
          <Link to="/error">Error</Link>
        </li>
        <li>
          <Link to="/swappage1326">Swappage1326</Link>
        </li>
        <li>
          <Link to="/swappage1920">Swappage1920</Link>
        </li>
        <li>
          <Link to="/liquidityconectwallet">Liquidityconectwallet</Link>
        </li>
        <li>
          <Link to="/uikit360liquiditypage">UiKit360Liquiditypage</Link>
        </li>
        <li>
          <Link to="/uikitliquiditypage">UIkitliquiditypage</Link>
        </li>
        <li>
          <Link to="/connectedwallet0">Connectedwallet0</Link>
        </li>
        <li>
          <Link to="/liquidityconnectedwalle">Liquidityconnectedwalle</Link>
        </li>
        <li>
          <Link to="/tokenpair">Tokenpair</Link>
        </li>
        <li>
          <Link to="/removeliquiditypopup">Removeliquiditypopup</Link>
        </li>
        <li>
          <Link to="/farmspage">Farmspage</Link>
        </li>
        <li>
          <Link to="/uikitfarmspage">UIKitFarmsPage</Link>
        </li>
        <li>
          <Link to="/uikitfarms">UIkitFarms</Link>
        </li>
        <li>
          <Link to="/uikitpoolsnew">UIkitpoolsnew</Link>
        </li>
        <li>
          <Link to="/poolspageredesigned">Poolspageredesigned</Link>
        </li>
        <li>
          <Link to="/poolswithwithdrawal">Poolswithwithdrawal</Link>
        </li>
        <li>
          <Link to="/poolpageuikit">PoolpageUIKit</Link>
        </li>
        <li>
          <Link to="/uikitreferralpage">Uikitreferralpage</Link>
        </li>
        <li>
          <Link to="/referralpage1326">Referralpage1326</Link>
        </li>
        <li>
          <Link to="/uikit360referralpage">UIKIT360REFERRALPAGE</Link>
        </li>
        <li>
          <Link to="/extraboostpage1920">ExtraBoostpage1920</Link>
        </li>
        <li>
          <Link to="/extraboostpage1326">ExtraBoostpage1326</Link>
        </li>
        <li>
          <Link to="/extraboostpagewithmor">ExtraBoostpagewithmor</Link>
        </li>
        <li>
          <Link to="/extraboostwithmoretas">ExtraBoostwithmoretas</Link>
        </li>
        <li>
          <Link to="/prelaunchwhite1920">PreLaunchwhite1920</Link>
        </li>
        <li>
          <Link to="/prelaunchwhite">PreLaunchwhite</Link>
        </li>
        <li>
          <Link to="/popupprelaunch">PopUpPreLaunch</Link>
        </li>
        <li>
          <Link to="/prelaunch">PreLaunch</Link>
        </li>
        <li>
          <Link to="/prelaunchblack">PreLaunchBlack</Link>
        </li>
        <li>
          <Link to="/prelaunchblackone">PreLaunchBlackOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
